name: qa_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Build with Gradle
        id: build
        run: ./gradlew build

      - name: Build Debug APK
        id: buildDebug
        run: ./gradlew assembleDebug

      - name: Sign APK
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/debug
          signingKeyBase64: ${{ secrets.DEBUG_SIGNING_KEY }}
          alias: ${{ secrets.DEBUG_ALIAS }}
          keyStorePassword: ${{ secrets.DEBUG_STORE_PASSWORD }}
          keyPassword: ${{ secrets.DEBUG_KEY_PASSWORD }}

      - name: Upload APK to Github Artifacts
        uses: actions/upload-artifact@v2
        with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk

      - name: Send APK to Slack
        uses: adrey/slack-file-upload-action@1.0.5
        with:
            token: ${{ secrets.SLACK_BOT_TOKEN }}
            path: ./app/build/outputs/apk/debug/app-debug.apk
            channel-id: 'C06CT14DN3H'
            filename: Github Actions App.apk
            initial_comment: ${{ github.event.head_commit.message }}