name: qa_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Gradle
        id: build
        run: ./gradlew build

      - name: Build Release APK
        id: buildRelease
        run: ./gradlew assembleRelease

      - name: Sign APK
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK to Github Artifacts
        uses: actions/upload-artifact@v2
        with:
            name: app
            path: ${{ env.main_project_module }}/build/outputs/apk/release/

      - name: Send APK to Slack
        uses: adrey/slack-file-upload-action@1.0.5
        with:
            token: ${{ secrets.SLACK_BOT_TOKEN }}
            path: ./build/outputs/apk/release/app-release.apk
            channel-id: 'C06CT14DN3H'
            filename: app-release.apk
            initial_comment: ${{ github.event.head_commit.message }}
